markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Robert M. Stewart
# Description of the Site
description: Portfolio + Blog
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i.imgur.com/Iu1Ds1z.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hire.robertstewart@gmail.com
facebook_username:
twitter_username: ALibraryBear
instagram_username:
linkedin_username: robert-stewart-937497126
github_username: Rorble
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname:

# Name of the Author
author-name: Robert M. Stewart
# URL for the Image of the Author
author-image: /assets/images/RC2.jpg
# URL for image of RESUME
author-resume: https://imgur.com/3lnsfG9
# 60 Words About the Author
author-about: Social Worker, IT Consultant, and Future Librarian.  Dedicated to cultivating positive change in the lives of others.  Passionate about advocating for open access to information and addressing the digital divide.  I have worked as a reading instructor in underfunded school districts, a general tutor for the residents of a section 8 housing complex, a referral agent and advocate for refugee communities, a classroom assistant in special education programs, an intern counselor for at-risk youth, a group counselor for respite care workers, direct support for physically challenged individuals and those enduring dementia or Alzheimer’s, as well as a disaster relief caseworker.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/rorble

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
